services:
  _default:
    autowire: true
    autoconfigure: true
    public: false

  trans_manager.type:
    class: Terra\TransManagerBundle\Type\TransManagerSubmitType
    tags: ['form.type']
    arguments:
      $key: '%trans_manager.key%'
      $secret: '%trans_manager.secret%'