<?php

namespace Terra\TransManagerBundle\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolver;

class TransManagerSubmitType extends AbstractType {

    private $key;

    private $secret;

    public function __construct($key, $secret)
    {
        $this->key = $key;
        $this->secret = $secret;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'mapped' => false
        ]);
//        parent::configureOptions($resolver); // TODO: Change the autogenerated stub
    }

    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['label'] = false;
        $view->vars['key'] = $this->key;
        $view->vars['secret'] = $this->secret;
        $view->vars['button'] = $options['label'];
    }

    public function getBlockPrefix()
    {
        return 'trans_manager_submit';
        //parent::getBlockPrefix(); // TODO: Change the autogenerated stub
    }

    public function getParent()
    {
        return TextType::class;
//        return parent::getParent(); // TODO: Change the autogenerated stub
    }
}